import type { ProductPageContent } from '@/lib/types/content';

export const productContent: ProductPageContent = {
  mainNavigation: {
    logo: {
      text: 'ILS One',
      href: '/',
    },
    categories: [
      {
        id: 'functionality',
        label: 'Functionality',
        items: [
          { id: 'highlights', label: 'Highlights', href: '#highlights', description: 'Key platform capabilities' },
          { id: 'platform', label: 'Platform', href: '#features', description: 'Full-lifecycle ILS tools' },
          { id: 'numbers', label: 'Product in Numbers', href: '#performance', description: 'Operational impact metrics' },
          { id: 'infrastructure', label: 'Infrastructure', href: '#design', description: 'Technical architecture' },
          { id: 'security', label: 'Security', href: '#security', description: 'Enterprise-grade protection' },
        ],
      },
      {
        id: 'company',
        label: 'Company',
        items: [
          { id: 'team', label: 'Team', href: '#team', description: 'Meet the people behind ILS One' },
          { id: 'vision', label: 'Vision & Mission', href: '#team', description: 'Our long-term commitment' },
        ],
      },
      {
        id: 'contact',
        label: 'Contact',
        href: '#contact',
        action: 'modal',
      },
    ],
    cta: {
      text: 'Launch App',
      href: 'https://ils.dev.iam-lab.ch',
    },
  },

  hero: {
    badge: 'Institutional Platform. On-Chain.',
    headline: 'ILS One',
    subheadline: 'Platform for Programmable Reinsurance',
    description: 'ILS One is a full lifecycle platform for Institutional Investors, Reinsurers, Brokers and Agents to transform insurance-linked securities into programmable on-chain instruments.',
    primaryCta: {
      text: 'Request Walkthrough',
      href: '#contact',
    },
    secondaryCta: {
      text: 'Launch App',
      href: 'https://ils.dev.iam-lab.ch',
    },
    productCards: [
      {
        id: 'volcanic',
        ticker: 'VDBO',
        price: '16$',
        title: 'Vulc... Bond (US)',
        description: 'Leverage the opportunities presented by insurance risks related to vulcanic activities.',
        redemptionDays: 26,
        expectedProfit: '+14%',
        image: 'https://images.unsplash.com/photo-1618681317438-a8dd7da06cd4?q=80&w=1740&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D',
        accentColor: '#a371f4',
        rotation: -15,
        translateY: 120,
      },
      {
        id: 'forest-fires',
        ticker: 'FFBO',
        price: '18$',
        title: 'Forest Fires Bond',
        description: 'Leverage the opportunities presented by insurance risks related to climate change.',
        redemptionDays: 42,
        expectedProfit: '+12%',
        image: 'https://images.unsplash.com/photo-1600181957881-b96c42bc6fab?q=80&w=776&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D',
        accentColor: '#f47171',
        rotation: -5,
        translateY: 20,
      },
      {
        id: 'floodings',
        ticker: 'FOBO',
        price: '7$',
        title: 'Floodings Bond',
        description: 'Leverage the opportunities presented by insurance risks related to floodings damage.',
        redemptionDays: 30,
        expectedProfit: '+18%',
        image: 'https://images.unsplash.com/photo-1619118905488-c2119fdb3dfd?q=80&w=1740&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D',
        accentColor: '#7185f4',
        rotation: 5,
        translateY: 0,
      },
      {
        id: 'hurricane',
        ticker: 'HUBO',
        price: '28$',
        title: 'Hurricane Bond',
        description: 'Leverage the opportunities presented by insurance risks related to hurricanes.',
        redemptionDays: 12,
        expectedProfit: '+22%',
        image: 'https://images.unsplash.com/photo-1454789476662-53eb23ba5907?q=80&w=904&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D',
        accentColor: '#f471c8',
        rotation: 12,
        translateY: 40,
      },
    ],
    trustBanner: {
      headline: 'Trusted by institutional leaders',
      subheadline: 'ILS One powers on-chain insurance-linked securities for leading asset managers, reinsurers and service providers',
      institutions: [
        { name: 'Hannover Re', logo: '/images/logos/HannoverRe.svg' },
        { name: 'Schroders', logo: '/images/logos/Schroders.png' },
        { name: 'Aon', logo: '/images/logos/AON.png' },
        { name: 'Hannover Re', logo: '/images/logos/HannoverRe.svg' },
        { name: 'Schroders', logo: '/images/logos/Schroders.png' },
        { name: 'Aon', logo: '/images/logos/AON.png' },
      ],
    },
  },

  navigation: [
    { id: 'hero', label: 'Overview', href: '#hero' },
    { id: 'highlights', label: 'Highlights', href: '#highlights' },
    { id: 'design', label: 'Infrastructure', href: '#design' },
    { id: 'security', label: 'Security', href: '#security' },
    { id: 'features', label: 'Platform', href: '#features' },
    { id: 'performance', label: 'Performance', href: '#performance' },
    { id: 'compare', label: 'Pricing', href: '#compare' },
    { id: 'specs', label: 'FAQ', href: '#specs' },
    { id: 'pricing', label: 'Pricing', href: '#pricing' },
  ],

  highlights: {
    headline: 'Programmable Reinsurance in Action',
    subheadline: 'Experience what efficiency feels like',
    tabs: [
      {
        id: 'governance',
        label: 'Governance',
        icon: '',
        lottieUrl: '/animations/highlights/multi-sig.json',
        videoUrl: '/animations/highlights/multi-sig.mp4',
        features: [
          {
            id: 'governance-main',
            icon: '',
            title: 'Multi-Signature Governance',
            description: 'Institutional-grade control for critical actions. Define approval thresholds, segregate roles and enforce governance directly on-chain.',
            image: 'https://images.unsplash.com/photo-1563013544-824ae1b704d3?w=600&q=80',
            badge: 'Enterprise',
          },
        ],
      },
      {
        id: 'configuration',
        label: 'Configuration',
        icon: '',
        lottieUrl: '/animations/highlights/product-config.json',
        videoUrl: '/animations/highlights/product-config.mp4',
        features: [
          {
            id: 'configuration-main',
            icon: '',
            title: 'Product Configuration',
            description: 'Configure reinsurance products through structured parameters instead of bespoke code. Pricing, limits, triggers and lifecycle rules — all auditable and transparent.',
            image: 'https://images.unsplash.com/photo-1551288049-bebda4e38f71?w=600&q=80',
          },
        ],
      },
      {
        id: 'automation',
        label: 'Automation',
        icon: '',
        lottieUrl: '/animations/highlights/lifecycle-automation.json',
        videoUrl: '/animations/highlights/lifecycle-automation.mp4',
        features: [
          {
            id: 'automation-main',
            icon: '',
            title: 'Lifecycle Automation',
            description: 'Automate the full lifecycle from subscription to settlement and redemption. Reduce operational friction while maintaining full control.',
            image: 'https://images.unsplash.com/photo-1485827404703-89b55fcc595e?w=600&q=80',
          },
        ],
      },
      {
        id: 'liquidity',
        label: 'Liquidity',
        icon: '',
        features: [
          {
            id: 'liquidity-main',
            icon: '',
            title: 'Secondary Marketplace',
            description: 'Enable 24/7 secondary trading of ILS positions in an institutional marketplace — unlocking flexibility and real liquidity.',
            image: 'https://images.unsplash.com/photo-1611974789855-9c2a0a7236a3?w=600&q=80',
          },
        ],
      },
    ],
  },

  design: {
    headline: 'Digital infrastructure for ILS',
    subheadline: 'Built to mirror legal reality — not disrupt it',
    description: 'ILS One is a smart-contract-based infrastructure that faithfully reflects existing legal structures while automating collateral flows, reporting and settlement.',
    features: [
      {
        title: 'Smart-Contract Templates',
        description: 'Create legally aligned agreements through guided click-through templates and deploy them on-chain with built-in controls.',
        image: '/images/infrastructure/sc-templates.png',
        imageAlt: 'Smart contract templates interface',
      },
      {
        title: 'Institutional DeFi, selectively applied',
        description: 'Integrate with Ethereum-based blockchains (EVM-compatible networks), stablecoins and institutional yield strategies — where they add real value.',
        image: '/images/infrastructure/yield.png',
        imageAlt: 'DeFi integrations',
      },
      {
        title: 'Auditability by default',
        description: 'Every action, approval and cashflow is traceable, timestamped and verifiable on-chain.',
        image: '/images/infrastructure/activity3.png',
        imageAlt: 'Audit trail visualization',
      },
    ],
  },

  security: {
    headline: 'Enterprise-grade security',
    subheadline: 'Built for institutional trust. Verified by industry leaders.',
    description: 'Security is embedded at every layer — from audited smart contracts to continuous monitoring. We meet the standards institutions demand.',
    credentials: [
      {
        id: 'audits',
        icon: 'audit',
        title: 'Tier-1 Security Audits',
        description: 'Smart contracts independently audited by leading blockchain security firms. Every line of code reviewed for vulnerabilities, logic errors and attack vectors. Audit reports available on request.',
        badge: 'Verified',
      },
      {
        id: 'pentest',
        icon: 'shield',
        title: 'Regular Security Testing',
        description: 'Application and UI undergo comprehensive penetration testing by certified security professionals. OWASP Top 10 coverage and beyond.',
        badge: 'Ongoing',
      },
      {
        id: 'non-custodial',
        icon: 'lock',
        title: 'Non-Custodial Architecture',
        description: 'Your assets remain in your control. ILS One never takes custody of funds — all transactions require your explicit multi-signature approval.',
      },
      {
        id: 'multi-sig',
        icon: 'users',
        title: 'Multi-Signature Protection',
        description: 'Critical operations require multiple authorized signatures, preventing single points of failure. Configure approval thresholds to match your governance requirements.',
      },
      {
        id: 'transparency',
        icon: 'eye',
        title: 'On-Chain Transparency',
        description: 'All contract logic is verifiable on-chain. No hidden functions, no admin backdoors, no upgrade keys that could compromise your assets.',
      },
      {
        id: 'monitoring',
        icon: 'activity',
        title: 'Continuous Monitoring',
        description: '24/7 automated monitoring for anomalies, suspicious transactions and potential threats. Incident response procedures tested and documented.',
      },
    ],
  },

  features: {
    headline: 'A full-lifecycle ILS platform',
    subheadline: 'From structuring to settlement — on one programmable stack',
    features: [
      {
        id: 'marketplace',
        badge: 'First-of-its-kind',
        headline: 'Institutional Marketplace',
        subheadline: 'Trade ILS positions without breaking structure',
        description: 'Enable controlled secondary trading of ILS agreements while preserving governance, compliance and transparency.',
        image: '/images/platform/marketplace.png',
        imageAlt: 'Marketplace interface',
        highlights: [
          'Secondary market access',
          '24/7 tradeability',
          'Institutional permissioning',
          'New capital flexibility',
        ],
        alignment: 'right',
      },
      {
        id: 'transactions',
        headline: 'Institutional Transactions',
        subheadline: 'Secure every transfer through multi-signature control',
        description: 'Self-custodial, role-based wallets designed for institutional workflows — not retail crypto UX.',
        image: '/images/platform/institutional-tx.png',
        imageAlt: 'Transaction management interface',
        highlights: [
          'Regulator-ready approvals',
          'Multi-signature protection',
          'Full transaction traceability',
          'Human-readable transactions',
        ],
        alignment: 'left',
      },
      {
        id: 'configurator',
        headline: 'Product Configurator',
        subheadline: 'Build deals from click-through templates',
        description: 'Turn legal agreements into executable smart contracts. Define triggers, roles, termination logic, run-off mechanics and settlement rules — without bespoke development.',
        image: '/images/platform/product-config.png',
        imageAlt: 'Product configurator interface',
        highlights: [
          'Template-based deal creation',
          'One-click token issuance',
          'Yield integration (optional)',
          'Single source of truth',
        ],
        alignment: 'right',
      },
      {
        id: 'roles',
        headline: 'Role-Based Interactions',
        subheadline: 'Pre-configured actions by role',
        description: 'Assign and enforce who can do what — directly at protocol level.',
        image: '/images/platform/roles.png',
        imageAlt: 'Role management interface',
        highlights: [
          'Role-guarded actions',
          'On-chain enforcement',
          'Fully traceable interactions',
          'Pseudonymous by design',
        ],
        alignment: 'left',
      },
    ],
  },

  performance: {
    headline: 'Product in Numbers',
    subheadline: 'Real operational impact, measurable results',
    engineName: 'ILS Vault Engine',
    engineDescription: 'A modular smart-contract architecture built for long-dated, multi-party financial products.',
    stats: [
      {
        id: 'settlement',
        value: 100,
        suffix: 'x',
        prefix: '',
        label: 'Faster Settlement',
        description: 'Down from 96 hours to 12 seconds',
      },
      {
        id: 'cost',
        value: 10,
        suffix: 'x',
        prefix: '',
        label: 'Less Costs',
        description: 'Reduced to 1% from 10% operational overhead',
      },
      {
        id: 'liquidity',
        value: 24,
        suffix: '/7',
        label: 'Liquidity',
        description: 'Deposit, Redeem or Trade anytime',
      },
      {
        id: 'audit',
        value: 100,
        suffix: '%',
        label: 'Auditable',
        description: 'Full on-chain traceability',
      },
    ],
    comparisons: [
      {
        label: 'Settlement Speed',
        ourValue: 99,
        ourDisplay: '12s',
        competitorValue: 1,
        competitorDisplay: '96h',
        unit: 'time to settle',
      },
      {
        label: 'Operational Cost',
        ourValue: 10,
        ourDisplay: '~1%',
        competitorValue: 100,
        competitorDisplay: '~10%',
        unit: 'of transaction',
      },
      {
        label: 'Audit Readiness',
        ourValue: 100,
        ourDisplay: '100%',
        competitorValue: 52,
        competitorDisplay: '52%',
        unit: 'traceability',
      },
    ],
  },

  comparison: {
    headline: 'Pay-per-transaction.',
    subheadline: 'No asset-based pricing. Fee structure is immutable once live.',
    tiers: [
      {
        id: 'included',
        name: 'Included',
        price: '$0',
        period: 'always',
        description: 'Core infrastructure at no cost',
        features: [
          { name: 'Institutional Wallets', included: true },
          { name: 'Portfolio View', included: true },
          { name: 'Transaction Execution', included: true },
          { name: 'Multi-Signature Governance', included: true },
          { name: 'Role-Based Permissions', included: true },
          { name: 'On-Chain Audit Trail', included: true },
        ],
        cta: { text: 'Get Started', href: 'https://ils.dev.iam-lab.ch' },
      },
      {
        id: 'usage',
        name: 'Usage-Based',
        price: 'Pay as you go',
        description: 'Pay only when you transact',
        features: [
          { name: 'Product Publishing', included: '$1,000' },
          { name: 'Subscription Fee', included: '0.25%' },
          { name: 'Redemption Fee', included: '0.75%' },
          { name: 'Secondary Market Fee', included: '1%' },
          { name: 'Renewal Fee', included: '0.25%' },
          { name: 'Custom Setup', included: 'Let\'s talk' },
        ],
        cta: { text: 'Request Walkthrough', href: '/demo' },
        highlighted: true,
      },
      {
        id: 'enterprise',
        name: 'Enterprise',
        price: 'Custom',
        description: 'For large organizations',
        features: [
          { name: 'Volume discounts', included: true },
          { name: 'Dedicated support', included: true },
          { name: 'Custom integrations', included: true },
          { name: 'SLA guarantees', included: true },
          { name: 'White-label options', included: true },
          { name: 'Priority feature requests', included: true },
        ],
        cta: { text: 'Contact Sales', href: '/contact' },
      },
    ],
  },

  specs: {
    headline: 'Frequently Asked Questions',
    subheadline: 'Everything you need to know before going on-chain',
    categories: [
      {
        id: 'general',
        title: 'General',
        icon: '',
        specs: [
          { label: 'What is ILS One?', value: 'ILS One is a programmable infrastructure for institutional insurance-linked securities, enabling automated collateral management, settlement, and secondary trading on-chain.' },
          { label: 'Do I need to change my legal structure?', value: 'No. ILS One mirrors existing legal structures while adding programmable automation. Your legal agreements remain the source of truth.' },
          { label: 'What blockchain does it use?', value: 'ILS One is built on EVM-compatible blockchains, enabling integration with stablecoins and institutional DeFi protocols where beneficial.' },
        ],
      },
      {
        id: 'security',
        title: 'Security & Compliance',
        icon: '',
        specs: [
          { label: 'How is custody handled?', value: 'Self-custodial architecture with multi-signature governance. You maintain full control of your assets at all times.' },
          { label: 'Is it regulator-ready?', value: 'Yes. Full audit trails, role-based permissions, and human-readable transaction records are built in from the ground up.' },
          { label: 'What about smart contract security?', value: 'All contracts are audited by leading security firms. We follow best practices for upgradability and emergency procedures.' },
        ],
      },
      {
        id: 'integration',
        title: 'Integration',
        icon: '',
        specs: [
          { label: 'How long does setup take?', value: 'Basic setup can be completed in days. Custom integrations typically take 2-4 weeks depending on complexity.' },
          { label: 'What systems can it integrate with?', value: 'ILS One provides APIs for integration with existing portfolio management, reporting, and compliance systems.' },
          { label: 'Is there documentation?', value: 'Comprehensive documentation, API references, and integration guides are available for all users.' },
        ],
      },
    ],
  },

  pricing: {
    headline: 'Ready to modernize your ILS operations?',
    subheadline: 'See how programmable reinsurance works in practice',
    description: 'Book a walkthrough and explore a live product setup.',
    price: 'Custom',
    period: '',
    features: [
      'Live product demonstration',
      'Architecture deep-dive',
      'Integration assessment',
      'Custom pricing discussion',
    ],
    cta: {
      text: 'Request Walkthrough',
      href: '/demo',
    },
    secondaryCta: {
      text: 'Read Documentation',
      href: '/docs',
    },
  },

  ctaFooter: {
    headline: 'The future of ILS infrastructure is programmable',
    subheadline: 'Built for institutions. Designed for reality.',
    cta: {
      text: 'Request Walkthrough',
      href: '/demo',
    },
    secondaryCta: {
      text: 'Contact Us',
      href: '/contact',
    },
  },

  audience: {
    headline: 'Who is it for',
    subheadline: 'Built for every participant in the ILS value chain',
    cards: [
      {
        id: 'institutional',
        title: 'Institutional Investors',
        painPoint: 'Illiquid, opaque ILS exposure with limited secondary market options',
        valueProposition: '24/7 liquidity, full transparency, and programmable positions',
        icon: 'institutional',
      },
      {
        id: 'reinsurer',
        title: 'Reinsurers',
        painPoint: 'Manual processes, slow settlement cycles, fragmented data',
        valueProposition: 'Automated lifecycle management and instant settlement',
        icon: 'reinsurer',
      },
      {
        id: 'broker',
        title: 'Brokers',
        painPoint: 'Fragmented intermediaries and disconnected workflows',
        valueProposition: 'Single platform with streamlined deal structuring',
        icon: 'broker',
      },
      {
        id: 'agent',
        title: 'Agents',
        painPoint: 'Limited access to capital and complex deal structuring',
        valueProposition: 'Direct market access with programmable agreements',
        icon: 'agent',
      },
    ],
  },

  team: {
    headline: 'The Team',
    vision: 'To create the infrastructure layer that makes institutional-grade reinsurance accessible, transparent, and programmable for the global market.',
    mission: 'We build the technical and operational foundations that enable insurance-linked securities to function as true digital instruments — without compromising on governance, compliance, or institutional standards.',
    members: [
      {
        id: 'member-1',
        name: 'Team Member',
        title: 'Co-Founder & CEO',
        image: '',
        previousCompanies: ['Previous Co'],
        funFact: 'Add a fun fact here',
      },
      {
        id: 'member-2',
        name: 'Team Member',
        title: 'Co-Founder & CTO',
        image: '',
        previousCompanies: ['Previous Co'],
        funFact: 'Add a fun fact here',
      },
      {
        id: 'member-3',
        name: 'Team Member',
        title: 'Head of Product',
        image: '',
        previousCompanies: ['Previous Co'],
        funFact: 'Add a fun fact here',
      },
      {
        id: 'member-4',
        name: 'Team Member',
        title: 'Head of Engineering',
        image: '',
        previousCompanies: ['Previous Co'],
        funFact: 'Add a fun fact here',
      },
    ],
  },

  footer: {
    company: {
      name: 'Invest One AG',
      legalEntity: 'Swiss Corporation (AG)',
      registryInfo: 'CHE-XXX.XXX.XXX',
      address: 'Löwenstrasse 29, 8001 Zürich, Switzerland',
      email: 'info@ils-one.com',
    },
    links: {
      impressum: '/impressum',
      privacy: '/privacy',
      legal: '/legal',
    },
    social: {
      twitter: 'https://twitter.com/ilsone',
      linkedin: 'https://linkedin.com/company/ils-one',
    },
  },
};
